from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    ActivityListView,
    AdminWebshopProductDetailView,
    AdminWebshopProductManageView,
    BookingCancelView,
    BookingDetailView,
    GuestBookingCreateView,
    BookingListCreateView,
    BookingRescheduleView,
    HealthcheckView,
    LoginView,
    MyBookingsView,
    MollieWebhookView,
    PaymentStatusView,
    PlanningDetailView,
    PlanningListCreateView,
    ProductListView,
    ProductGroupListView,
    ProductDetailView,
    ProfileView,
    RoomListView,
    RegisterView,
    RoleCheckView,
    TimeslotAvailabilityView,
    WebshopOrderCreateView,
)

urlpatterns = [
    path("healthz/", HealthcheckView.as_view(), name="healthz"),
    path("product-groups/", ProductGroupListView.as_view(), name="product-groups"),
    path("products/", ProductListView.as_view(), name="products"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("admin/webshop/products/", AdminWebshopProductManageView.as_view(), name="admin-webshop-products"),
    path("admin/webshop/products/<int:pk>/", AdminWebshopProductDetailView.as_view(), name="admin-webshop-product-detail"),
    path("webshop/orders/", WebshopOrderCreateView.as_view(), name="webshop-order-create"),
    path("activities/", ActivityListView.as_view(), name="activities"),
    path("rooms/", RoomListView.as_view(), name="rooms"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="auth-token-refresh"),
    path("auth/profile/", ProfileView.as_view(), name="auth-profile"),
    path("auth/role-check/", RoleCheckView.as_view(), name="auth-role-check"),
    path("planning/", PlanningListCreateView.as_view(), name="planning-list-create"),
    path("planning/<int:pk>/", PlanningDetailView.as_view(), name="planning-detail"),
    path("timeslots/available/", TimeslotAvailabilityView.as_view(), name="timeslot-available"),
    path("bookings/", BookingListCreateView.as_view(), name="booking-list-create"),
    path("bookings/guest/", GuestBookingCreateView.as_view(), name="booking-guest-create"),
    path("bookings/mine/", MyBookingsView.as_view(), name="booking-mine"),
    path("bookings/<int:pk>/", BookingDetailView.as_view(), name="booking-detail"),
    path("bookings/<int:pk>/cancel/", BookingCancelView.as_view(), name="booking-cancel"),
    path("bookings/<int:pk>/reschedule/", BookingRescheduleView.as_view(), name="booking-reschedule"),
    path("payments/status/<uuid:public_reference>/", PaymentStatusView.as_view(), name="payment-status"),
    path("payments/mollie/webhook/", MollieWebhookView.as_view(), name="payments-mollie-webhook"),
]
