# Generated by Copilot on 2026-06-14
from decimal import Decimal
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_booking_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="price",
            field=models.DecimalField(decimal_places=2, default=Decimal("25.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="public_reference",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
